In [1]:
import numpy as np

# Sistema de ecuaciones lineales usando Gauss

In [2]:
def gauss(g):
    """Eliminación de gauss jordan"""
    n = g.shape[0]
    for i in range(n):
        g[i] = g[i] / g[i][i]
        # print(g)
        for j in range(n):
            if i != j:
                g[j] = g[j] - g[i] * g[j][i]
                # print(g)
    variables = [column[n] for column in g]
    # print(g)
    return variables

In [3]:
g = np.array([[-2, 2, 1, 20], [-2, 4, 1, 268], [-1, 1, 2, 190]])
g = g.astype(np.float64)
v = gauss(g)
print(v)

[174.0, 124.0, 120.0]


# Inversa de una matriz usando gauss

In [4]:
A = np.array(
    [
        [1, 1, 1, 1, 1, 0, 0, 0],
        [2, 1, 2, -1, 0, 1, 0, 0],
        [1, 4, 3, 1, 0, 0, 1, 0],
        [3, 3, 1, 1, 0, 0, 0, 1],
    ]
)

A = A.astype(np.float64)

n = A.shape[0]
m = A.shape[1]

for i in range(n):
    # convierte los elementos de la diagonal en 1
    A[i] = A[i] / A[i][i]
    # recorre cada columna y convierte todos sus elementos excepto los valores de la diagonal (aii) en 0
    for j in range(n):
        if i != j:
            A[j] = A[j] - A[i] * A[j][i]
for i in range(int(m / 2)):
    A = np.delete(A, (0), axis=1)

print(A)

[[ 0.22727273  0.18181818 -0.27272727  0.22727273]
 [-0.72727273 -0.18181818  0.27272727  0.27272727]
 [ 0.59090909  0.27272727  0.09090909 -0.40909091]
 [ 0.90909091 -0.27272727 -0.09090909 -0.09090909]]


# Factorizacion LU (Gauss)

In [5]:
# A = np.array([[ 1, 1, 1],
#              [ 2, 3, 5],
#              [ 4, 6, 8]])

# A = np.array([[ -2, 4,  1],
#              [ 4, -5,  4],
#              [ -6,  -3,  -14]])

A = np.array([[-2, 2, 1], [-2, 4, 1], [-1, 1, 2]])
A = A.astype(np.float64)
U = A
n = A.shape[0]
L = np.identity(n, np.float64)

E = []
for i in range(n):
    for j in range(n):
        if i < j:
            # print("Matriz Elemental")
            # I = np.identity(n, np.float64)
            L[j][i] = U[j][i] / U[i][i]
            # print(L)
            E.append(L)
            # print("Matriz A Convertida")
            U[j] = U[j] - (U[i] * U[j][i]) / U[i][i]
            # print(U)

print("Matriz U: ")
print(U)

print("Matriz L: ")
print(L)

print("Verificar factorizacion A=L*U: ")
print(np.dot(L, U))

Matriz U: 
[[-2.   2.   1. ]
 [ 0.   2.   0. ]
 [ 0.   0.   1.5]]
Matriz L: 
[[1.  0.  0. ]
 [1.  1.  0. ]
 [0.5 0.  1. ]]
Verificar factorizacion A=L*U: 
[[-2.  2.  1.]
 [-2.  4.  1.]
 [-1.  1.  2.]]


In [6]:
b = np.array([20.0, 268.0, 190.0])
L = np.insert(L, L.shape[1], b, 1)
y = gauss(L)
U = np.insert(U, U.shape[1], y, 1)
x = gauss(U)
print(x)

[174.0, 124.0, 120.0]


# Factorización LU (crout)

In [7]:
A = np.array([[-2, 2, 1], [-2, 4, 1], [-1, 1, 2]])
A = A.astype(np.float64)
n = A.shape[0]

L = np.zeros((n, n), dtype=np.float64)
U = np.identity(n, dtype=np.float64)


for j in range(0, n):
    for i in range(0, j):
        sum0 = sum([L[i, k] * U[k, j] for k in range(0, i)])
        U[i, j] = (A[i, j] - sum0) / L[i, i]

    for i in range(j, n):
        sum1 = sum([L[i, k] * U[k, j] for k in range(0, j)])
        L[i, j] = (A[i, j] - sum1) / U[j, j]

print("Matriz U: ")
print(U)

print("Matriz L: ")
print(L)

print("Verificar factorizacion A=L*U: ")
print(np.dot(L, U))

b = np.array([20.0, 268.0, 190.0])
L = np.insert(L, L.shape[1], b, 1)
y = gauss(L)
U = np.insert(U, U.shape[1], y, 1)
x = gauss(U)
print(x)

Matriz U: 
[[ 1.  -1.  -0.5]
 [ 0.   1.   0. ]
 [ 0.   0.   1. ]]
Matriz L: 
[[-2.   0.   0. ]
 [-2.   2.   0. ]
 [-1.   0.   1.5]]
Verificar factorizacion A=L*U: 
[[-2.  2.  1.]
 [-2.  4.  1.]
 [-1.  1.  2.]]
[174.0, 124.0, 120.0]


# Factorización LU (Doolitle)

In [8]:
A = np.array([[-2, 2, 1], [-2, 4, 1], [-1, 1, 2]])
A = A.astype(np.float64)
n = A.shape[0]

U = np.zeros((n, n), dtype=np.float64)
L = np.identity(n, dtype=np.float64)


for i in range(0, n):
    for j in range(0, i):
        sum0 = sum([L[i, k] * U[k, j] for k in range(0, j)])
        L[i, j] = (A[i, j] - sum0) / U[j, j]

    for j in range(i, n):
        sum1 = sum([L[i, k] * U[k, j] for k in range(0, i)])
        U[i, j] = (A[i, j] - sum1) / L[i, i]

print("Matriz U: ")
print(U)

print("Matriz L: ")
print(L)

print("Verificar factorizacion A=L*U: ")
print(np.dot(L, U))

b = np.array([20.0, 268.0, 190.0])
L = np.insert(L, L.shape[1], b, 1)
y = gauss(L)
U = np.insert(U, U.shape[1], y, 1)
x = gauss(U)
print(x)

Matriz U: 
[[-2.   2.   1. ]
 [ 0.   2.   0. ]
 [ 0.   0.   1.5]]
Matriz L: 
[[1.  0.  0. ]
 [1.  1.  0. ]
 [0.5 0.  1. ]]
Verificar factorizacion A=L*U: 
[[-2.  2.  1.]
 [-2.  4.  1.]
 [-1.  1.  2.]]
[174.0, 124.0, 120.0]


# Algoritmo $LDL^T$

In [10]:
A = np.array([[4, 1, 1, 1], [1, 3, -1, 1], [1, -1, 2, 0], [1, 1, 0, 2]])
n = A.shape[0]


L = np.zeros((n, n))
D = np.zeros((n, n))


for i in range(0, n):
    sum0 = sum([L[i][j] * L[i][j] * D[j][j] for j in range(0, i)])
    D[i][i] = A[i][i] - sum0
    for j in range(i, n):
        sum1 = sum([L[j][k] * L[i][k] * D[k][k] for k in range(0, i)])
        L[j][i] = (A[j][i] - sum1) / D[i][i]
print(D)
print(L)
print("Verificar factorizacion A = L*D*L^T: ")
c = np.dot(L, D)
print((np.dot(c, L.transpose())))

[[4.         0.         0.         0.        ]
 [0.         2.75       0.         0.        ]
 [0.         0.         1.18181818 0.        ]
 [0.         0.         0.         1.53846154]]
[[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [ 0.25       -0.45454545  1.          0.        ]
 [ 0.25        0.27272727  0.07692308  1.        ]]
Verificar factorizacion A = L*D*L^T: 
[[ 4.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00  2.13504428e-18]
 [ 1.00000000e+00  1.00000000e+00 -1.38777878e-17  2.00000000e+00]]


# Algoritmo de Cholesky

In [11]:
A = np.array([[4, 1, 1, 1], [1, 3, -1, 1], [1, -1, 2, 0], [1, 1, 0, 2]])
n = A.shape[0]


L = np.zeros((n, n))
# D = np.zeros((n,n))


for i in range(0, n):
    sum0 = sum([L[i][j] * L[i][j] for j in range(0, i)])
    L[i][i] = (A[i][i] - sum0) ** (0.5)
    for j in range(i, n):
        sum1 = sum([L[j][k] * L[i][k] for k in range(0, i)])
        L[j][i] = (A[j][i] - sum1) / L[i][i]
# print(D)
print(L)
print(L.transpose())
print("Verificar factorizacion A = L*L^T: ")
# c = np.dot(L, D)
print(np.dot(L, L.transpose()))

[[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]
[[ 2.          0.5         0.5         0.5       ]
 [ 0.          1.6583124  -0.75377836  0.45226702]
 [ 0.          0.          1.08711461  0.0836242 ]
 [ 0.          0.          0.          1.24034735]]
Verificar factorizacion A = L*L^T: 
[[ 4.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00 -1.41926118e-17]
 [ 1.00000000e+00  1.00000000e+00 -1.41926118e-17  2.00000000e+00]]


# Parlett y Reid

In [12]:
A = np.array([[0, 1, 2, 3], [1, 2, 2, 2], [2, 2, 3, 3], [3, 2, 3, 4]])

A1 = A
n = A.shape[0]
ind = np.arange(0, n)
I = np.eye(n)
P = I
M = I
L = I
for i in range(0, n - 2):
    mayor = np.amax(A[i, i + 1: n])
    index = np.where(A[i, i + 1: n] == np.amax(A[i, i + 1: n]))[0][0]
    index = index + i
    p = ind
    p[i + 1] = index
    p[index] = i + 1
    per = I[:, p]
    A = np.dot(np.dot(per, A), per.T)
    P = np.dot(per, P)
    L[i + 1: n, i] = L[p[i + 1: n], i]
    m = np.zeros(n)
    for j in range(i + 2, n):
        m[j] = A[i, j] / mayor
    mult = I - np.dot(m, I[:, i + 1].T)
    A = np.dot(np.dot(mult, A), mult.T)
    M = np.dot(mult, M)
    L = L - np.tril(mult, -1)
T = A
print(T)
print(L)
print(M)
print(P)
print(A)
# PAPT= LTLT
x = np.dot(np.dot(P, A1), P.T)
x
y = np.dot(np.dot(L, T), L.T)
print("La forma PAPT es: ")
print(x)
print("La forma LMLT es: ")
print(y)

[[0. 0. 3. 3.]
 [0. 0. 0. 0.]
 [3. 0. 9. 5.]
 [3. 0. 5. 4.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 3. 3.]
 [0. 0. 0. 0.]
 [3. 0. 9. 5.]
 [3. 0. 5. 4.]]
La forma PAPT es: 
[[0. 0. 3. 3.]
 [0. 0. 0. 0.]
 [3. 0. 9. 5.]
 [3. 0. 5. 4.]]
La forma LMLT es: 
[[0. 0. 3. 3.]
 [0. 0. 0. 0.]
 [3. 0. 9. 5.]
 [3. 0. 5. 4.]]
